# This is a basic workflow to help you get started with Actions

name: CI for Azure Learning

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Azure at home!

    # Runs a set of commands using the runners shell
    #- name: Run a multi-line script
      #run: |
        #echo Add other actions to build,
        #echo test, and deploy your project.
        
    # Run spell check:
    #- name: Check spelling
      #uses: check-spelling/check-spelling@0.0.14-alpha
    
    #Run Mardown checker:
    - name: Markdown Linting Action
      uses: avto-dev/markdown-lint@v1.1.0
      #with:
        # Custom rule files (file|directory|glob|package)
        #rules: # optional
        # Configuration file (JSON, JSONC, or YAML)
        #config: # optional
        # Fix basic errors
        #fix: # optional, default is false
        # Write issues to file
        #output: # optional
        # Files to ignore/exclude
        #ignore: # optional
        # Files (directories|globs) for a work or any additional arguments
        #args: 
